### ISSUE TITLE
PsiphonLinux 

### ISSUE THREAD

**Issue by Tem85** [SpherionOS/PsiphonLinux#3]
Hello SpherionOS. Please tell me how to launch a specific region in PsiphonLinux? So that when turned on, the same country is always in touch.

**Comment by SpherionOS** [comment]
I've found a parameter called "EgressRegion". Inserting this into the psiphon.config file with your target country should tell Psiphon to choose servers from that specific region. Here is the modified psiphon.config example.

`{
"LocalHttpProxyPort":8081,
"LocalSocksProxyPort":1081,
"EgressRegion":"US",
"PropagationChannelId":"FFFFFFFFFFFFFFFF",
"RemoteServerListDownloadFilename":"remote_server_list",
"RemoteServerListSignaturePublicKey":"MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiV>"RemoteServerListUrl":"https://s3.amazonaws.com//psiphon/web/mjr4-p23r-puwl/server_list_compressed",
"SponsorId":"FFFFFFFFFFFFFFFF",
"UseIndistinguishableTLS":true
}`

I have changed "EgressRegion":"US", to US and it should hopefully put you in the right region. Change the region code to the country you want when you use it.. Try this on your linux device to see if it works. My onsite linux lab is being funky and I can't test right now. Lmk how it goes

**Comment by Tem85** [comment]
Thanks a lot! Everything is working! You are the best!

**Comment by SpherionOS** [comment]
I'm glad it worked. I'll close this issue and update the documentation to show how to change regions.

**Comment by imaniy1994** [comment]
Hello, I followed all the steps correctly.

After executing the following command, I get an error that the psiphon.config file does not exist:
`./'psiphon-tunnel-core-x86_64' -config psiphon.config`

I manually create this file and execute the above command again and the following error is displayed to me:
`{"data":{"message":"error processing configuration file: psiphon.LoadConfig#907: invalid character 'R' after object key:value pair"},"noticeType":"Error","timestamp":"2024-07-29T08:17:25.149Z"}`

Ubuntu 22

**Comment by SpherionOS** [comment]
By "manually created this file" do you mean you wrote it out instead of copy pasting? Could there be a mistake while writing it? I'll rerun this code on an Ubuntu 22 vm to see if i get any errors there.

**Comment by imaniy1994** [comment]
> By "manually created this file" do you mean you wrote it out instead of copy pasting? Could there be a mistake while writing it? I'll rerun this code on an Ubuntu 22 vm to see if i get any errors there.

No.
I created this file by `nano psiphon.config` command and put the above code by copy pasting and received this error.

sorry my english not very good :(

**Comment by SpherionOS** [comment]
Thats all good, thank you for the clarification, I'm looking into it now

**Comment by imaniy1994** [comment]
> Could you copy paste the config file you have here so I can look at it?

The contents of this file are exactly the same codes that you put above:

`{ "LocalHttpProxyPort":8081, "LocalSocksProxyPort":1081, "EgressRegion":"US", "PropagationChannelId":"FFFFFFFFFFFFFFFF", "RemoteServerListDownloadFilename":"remote_server_list", "RemoteServerListSignaturePublicKey":"MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiV>"RemoteServerListUrl":"https://s3.amazonaws.com//psiphon/web/mjr4-p23r-puwl/server_list_compressed", "SponsorId":"FFFFFFFFFFFFFFFF", "UseIndistinguishableTLS":true }`

As I said before, when I type the following command, (`./'psiphon-tunnel-core-x86_64' -config psiphon.config`) it says that the psiphon.config file does not exist, and I create it with the `nano psiphon.config` command and put the contents you said in it.

**Comment by smblue07** [comment]
Hello to fix the location
Edit the file /etc/psiphon/psiphon.config with nano
Put the location in the 3 line, it will be ok, for example:
 {
 "LocalHttpProxyPort":8081,
 "LocalSocksProxyPort":1081,
 "EgressRegion":"US",
 ....
}

**Comment by hero007ir** [comment]
> Hello to fix the location Edit the file /etc/psiphon/psiphon.config with nano Put the location in the 3 line, it will be ok, for example: { "LocalHttpProxyPort":8081, "LocalSocksProxyPort":1081, "EgressRegion":"US", .... }

Thanks a lot! Everything works great!

**Comment by iaghapour** [comment]
Script training in Persian and English subtitles:

https://youtu.be/d3xJbxA9nGM?si=Rj173r21yyNzClNn

**Comment by tsunamihell** [comment]
first create config file 
nano config.json
Copy and paste the following JSON content into the nano editor:
{
  "LocalHttpProxyPort": 8081,
  "LocalSocksProxyPort": 1081,
  "EgressRegion": "US",
  "PropagationChannelId": "FFFFFFFFFFFFFFFF",
  "RemoteServerListDownloadFilename": "remote_server_list",
  "RemoteServerListSignaturePublicKey": "MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiV",
  "RemoteServerListUrl": "https://s3.amazonaws.com//psiphon/web/mjr4-p23r-puwl/server_list_compressed",
  "SponsorId": "FFFFFFFFFFFFFFFF",
  "UseIndistinguishableTLS": true
}
Save this content as a file named config.json

chmod +x psiphon-tunnel-core-x86_64

then 
./psiphon-tunnel-core-x86_64 -config config.json

You can specify different egress regions in the configuration file to control the country from which your traffic appears to originate. Here’s a list of available regions you can use:

"regions":["AT","BE","BG","CA","CH","CZ","DE","DK","EE","ES","FI","FR","GB","HU","IE","IN","IT","JP","NL","NO","PL","RO","RS","SE","SK","US"]

**Comment by mahsamcse** [comment]
> first create config file nano config.json Copy and paste the following JSON content into the nano editor: { "LocalHttpProxyPort": 8081, "LocalSocksProxyPort": 1081, "EgressRegion": "US", "PropagationChannelId": "FFFFFFFFFFFFFFFF", "RemoteServerListDownloadFilename": "remote_server_list", "RemoteServerListSignaturePublicKey": "MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiV", "RemoteServerListUrl": "https://s3.amazonaws.com//psiphon/web/mjr4-p23r-puwl/server_list_compressed", "SponsorId": "FFFFFFFFFFFFFFFF", "UseIndistinguishableTLS": true } Save this content as a file named config.json
> 
> chmod +x psiphon-tunnel-core-x86_64
> 
> then ./psiphon-tunnel-core-x86_64 -config config.json
> 
> You can specify different egress regions in the configuration file to control the country from which your traffic appears to originate. Here’s a list of available regions you can use:
> 
> "regions":["AT","BE","BG","CA","CH","CZ","DE","DK","EE","ES","FI","FR","GB","HU","IE","IN","IT","JP","NL","NO","PL","RO","RS","SE","SK","US"]

error
root@8888:~# sudo chmod +x psiphon-tunnel-core-x86_64
chmod: cannot access 'psiphon-tunnel-core-x86_64': No such file or directory

**Comment by tsunamihell** [comment]
> > first create config file nano config.json Copy and paste the following JSON content into the nano editor: { "LocalHttpProxyPort": 8081, "LocalSocksProxyPort": 1081, "EgressRegion": "US", "PropagationChannelId": "FFFFFFFFFFFFFFFF", "RemoteServerListDownloadFilename": "remote_server_list", "RemoteServerListSignaturePublicKey": "MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiV", "RemoteServerListUrl": "https://s3.amazonaws.com//psiphon/web/mjr4-p23r-puwl/server_list_compressed", "SponsorId": "FFFFFFFFFFFFFFFF", "UseIndistinguishableTLS": true } Save this content as a file named config.json
> > chmod +x psiphon-tunnel-core-x86_64
> > then ./psiphon-tunnel-core-x86_64 -config config.json
> > You can specify different egress regions in the configuration file to control the country from which your traffic appears to originate. Here’s a list of available regions you can use:
> > "regions":["AT","BE","BG","CA","CH","CZ","DE","DK","EE","ES","FI","FR","GB","HU","IE","IN","IT","JP","NL","NO","PL","RO","RS","SE","SK","US"]
> 
> error root@8888:~# sudo chmod +x psiphon-tunnel-core-x86_64 chmod: cannot access 'psiphon-tunnel-core-x86_64': No such file or directory.

Ensure you have downloaded the psiphon-tunnel-core-x86_64 executable file. Place it in your desired directory.If you have not downloaded it yet, do so from the official source.

**Comment by hamedefatian** [comment]
> first create config file nano config.json Copy and paste the following JSON content into the nano editor: { "LocalHttpProxyPort": 8081, "LocalSocksProxyPort": 1081, "EgressRegion": "US", "PropagationChannelId": "FFFFFFFFFFFFFFFF", "RemoteServerListDownloadFilename": "remote_server_list", "RemoteServerListSignaturePublicKey": "MIICIDANBgkqhkiG9w0BAQEFAAOCAg0AMIICCAKCAgEAt7Ls+/39r+T6zNW7GiV", "RemoteServerListUrl": "https://s3.amazonaws.com//psiphon/web/mjr4-p23r-puwl/server_list_compressed", "SponsorId": "FFFFFFFFFFFFFFFF", "UseIndistinguishableTLS": true } Save this content as a file named config.json
> 
> chmod +x psiphon-tunnel-core-x86_64
> 
> then ./psiphon-tunnel-core-x86_64 -config config.json
> 
> You can specify different egress regions in the configuration file to control the country from which your traffic appears to originate. Here’s a list of available regions you can use:
> 
> "regions":["AT","BE","BG","CA","CH","CZ","DE","DK","EE","ES","FI","FR","GB","HU","IE","IN","IT","JP","NL","NO","PL","RO","RS","SE","SK","US"]

thanks,
its work for me;
is there anyway to use 2 or more location?
