### ISSUE TITLE
I cant start service in ARM64 (Ampere)

### ISSUE THREAD

**Issue by BehnamSaedi** [SpherionOS/PsiphonLinux#6]
Hello, I could not run the service on a server with ARM64 
It has this error at runtime
/usr/bin/psiphon: line 3: /etc/psiphon/psiphon-tunnel-core-x86_64: cannot execute binary file: Exec format error

Thank you, check this out

**Comment by SpherionOS** [comment]
The binary included in this repository is the x86 binary, which is a different CPU architecture to ARM64. There may be binaries available for ARM64, but it is not supported by this repository.
