### ISSUE TITLE
How can i change location and choose the best server

### ISSUE THREAD

**Issue by a3shkn** [SpherionOS/PsiphonLinux#7]
Hi
I want to choose a location that can give me the best performance.

**Comment by SpherionOS** [comment]
I'm unsure if theres a way that does it automatically, but if you look for a nearby country, it should increase performance by changing your egress region. The instructions for this are in the readme FAQ section. Psiphon is soft capped at 2Mbps i believe so that also contributes to performance.

**Comment by THMaST3R** [comment]
can you add ukrain to psiphon servers pls

**Comment by SpherionOS** [comment]
> can you add ukrain to psiphon servers pls

I dont have control over the Psiphon server list, the servers provided are from Psiphon Inc themselves

**Comment by THMaST3R** [comment]
> > can you add ukrain to psiphon servers pls
> 
> I dont have control over the Psiphon server list, the servers provided are from Psiphon Inc themselves

they have ukrain server on pc and android app
but we can't access to that server on linux
i hope u can do anything for that
